import React, { useMemo } from 'react';
import {
  WordSpirit,
  SpiritSpecies,
  generateWordSpirit,
  getSpiritLevel,
  getSpiritSize,
} from '@/utils/WordSpiritGenerator';

// ─── 像素圖案定義 ───────────────────────────────────
// 每個圖案是 16×16 的字元矩陣
// P = primary, S = secondary, E = eye, W = white highlight, . = transparent

type PixelChar = '.' | 'P' | 'S' | 'E' | 'W';
type PixelGrid = PixelChar[][];

const PATTERNS: Record<SpiritSpecies, string[]> = {
  cat: [
    '....P...........',
    '...PP....PP.....',
    '..PPP....PPP....',
    '..PPPP..PPPP....',
    '..PPPPPPPPPP....',
    '..PEWPPPPWEP....',
    '..PPPPSSPPP.....',
    '..PPPSSSPPP.....',
    '...PPPPPPPP.....',
    '...PPPPPPPP.....',
    '...SSPPPPSS.....',
    '..SSPPPPPPSS....',
    '..SSPPPPPPSS....',
    '..SS..PP..SS....',
    '..SS..PP..SS....',
    '..SS......SS....',
  ],
  dog: [
    '....PPPP........',
    '..SSPPPPSS......',
    '..SSPPPPSS......',
    '...PPPPPPPP.....',
    '..PPPPPPPPPP....',
    '..PEWPPPPWEP....',
    '..PPPPPPPPPP....',
    '..PPPSSSPPP.....',
    '...PPSSPPP......',
    '...PPPPPPPP.....',
    '...SPPPPPPS.....',
    '..SSPPPPPPSS....',
    '..SSPPPPPPSS....',
    '...SS.PP.SS.....',
    '...SS.PP.SS.....',
    '...SS....SS.....',
  ],
  rabbit: [
    '....PP....PP....',
    '...PPP...PPP....',
    '...PPP...PPP....',
    '...PPP...PPP....',
    '...PPPPPPPP.....',
    '..PPPPPPPPPP....',
    '..PEWPPPPWEP....',
    '..PPPPPPPPPP....',
    '..PPPSSSPPP.....',
    '...PPPPPPPP.....',
    '...PPPPPPPP.....',
    '...SSPPPPSS.....',
    '..SSPPPPPPSS....',
    '..SS..PP..SS....',
    '..SS..PP..SS....',
    '..SSS....SSS....',
  ],
  bird: [
    '......PPP.......',
    '.....PPPPP......',
    '....PPPPPPP.....',
    '...PPPPPPPP.....',
    '...PEWPPPPP.....',
    '..PPPPPPPPSS....',
    '..PPPPPPPPPP....',
    '.PPPPPPPPPPP....',
    'PPPPPPPPPPPP....',
    '.PPPPPPPPPP.....',
    '..PPPPPPPP......',
    '...PPPPPP.......',
    '....PPPP........',
    '...SS..SS.......',
    '...SS..SS.......',
    '..SSS..SSS......',
  ],
  fish: [
    '................',
    '......PPP.......',
    '....PPPPPPP.....',
    '...PPPPPPPPPS...',
    '..PPPPPPPPPPSSS.',
    '..PEWPPPPPPP.SS.',
    '.PPPPPPPPPPPSS..',
    '.PPPPSPPPPPPSSS.',
    '.PPPPSSPPPPPSS..',
    '..PPPPPPPPPP....',
    '..PPPPPPPPPP....',
    '...PPPPPPPPS....',
    '....PPPPPPPSSS..',
    '.....PPPPP.SSS..',
    '......PPP.......',
    '................',
  ],
  snake: [
    '................',
    '......PPPP......',
    '.....PPPPPP.....',
    '....PPPPPPPP....',
    '...PEWPPWEP.....',
    '...PPPSSSPPP....',
    '...PPPPPPPPP....',
    '....PPPPPPP.....',
    '...PPPPPPP......',
    '..PPPPPPP.......',
    '.PPPPPPP........',
    '..PPPPPPP.......',
    '...PPPPPPP......',
    '....PPPPPPPP....',
    '.....PPPPPPP....',
    '......SSSSSS....',
  ],
  dragon: [
    '..WW........WW..',
    '..PPP......PPP..',
    '..PPPP....PPPP..',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '..PEWPPPPPPWEP..',
    '..PPPPPPPPPPPP..',
    '..PPPPSSSSPPPP..',
    '...PPPPPPPPPP...',
    '..SSPPPPPPPPSS..',
    '..SSPPPPPPPPSS..',
    '.SSS.PPPPPP.SSS.',
    '.SS..PPPPPP..SS.',
    '.SS..SS..SS..SS.',
    '.SS..SS..SS..SS.',
    '.SS..SS..SS..SS.',
  ],
  fox: [
    '..PP........PP..',
    '..PPP......PPP..',
    '..SPPP....PPPS..',
    '..SSPPPPPPPPSS..',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '..PEWPPPPPPWEP..',
    '..PPPPPPPPPPPP..',
    '..PPWPSSSPWPP...',
    '...WWPPPPPWW....',
    '...PPPPPPPPPP...',
    '..SSPPPPPPPPSS..',
    '..SS.PPPPPP.SS..',
    '..SS..PP.PP.SS..',
    '......PP.PP.....',
    '......SS.SS.....',
  ],
  bear: [
    '..PP........PP..',
    '.PPPP......PPPP.',
    '.PPPP......PPPP.',
    '..PPPPPPPPPPPP..',
    '..PPPPPPPPPPPP..',
    '..PEWPPPPPPWEP..',
    '..PPPPPPPPPPPP..',
    '..PPPSSSSSPPPP..',
    '...PPPPPPPPPP...',
    '..SSPPPPPPPPSS..',
    '..SSPPPPPPPPSS..',
    '..SSPPPPPPPPSS..',
    '..SS.PPPPPP.SS..',
    '..SS..PPPP..SS..',
    '..SS..PPPP..SS..',
    '.SSS..SSSS..SSS.',
  ],
  wolf: [
    '..PP........PP..',
    '..PPP......PPP..',
    '..PPPP....PPPP..',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '..PEWPPPPPPWEP..',
    '..PPPPPPPPPPPP..',
    '..PPPPSSSPPPPP..',
    '..PPPSSSSSPPPP..',
    '...PPPPPPPPPP...',
    '...SSPPPPPPSS...',
    '..SSPPPPPPPPSS..',
    '..SS.PPPPPP.SS..',
    '..SS..PP.PP.SS..',
    '......PP.PP.....',
    '.....SSS.SSS....',
  ],
  deer: [
    '.WW..........WW.',
    '.WPW........WPW.',
    '.WWPW......WPWW.',
    '...PPP....PPP...',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '..PEWPPPPPPWEP..',
    '..PPPPPPPPPPPP..',
    '..PPPPSSPPPPP...',
    '...PPPPPPPPPP...',
    '...SSPPPPPPSS...',
    '..SSPPPPPPPPSS..',
    '..SS.PPPPPP.SS..',
    '..SS..PP.PP.SS..',
    '......PP.PP.....',
    '.....SSS.SSS....',
  ],
  owl: [
    '....PPPPPPPP....',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '.PWWPPPPPPPWWP..',
    '.PWEEPPPPPWEEP..',
    '.PWWPPPPPPPWWP..',
    '..PPPPPSPPPP....',
    '..PPPPSSPPPPP...',
    '...PPPPPPPPPP...',
    '...SSPPPPPPSS...',
    '..SSSPPPPPPSSS..',
    '..SS.PPPPPP.SS..',
    '..SS.PPPPPP.SS..',
    '.....PP..PP.....',
    '.....PP..PP.....',
    '....SSS..SSS....',
  ],
  lion: [
    '....P...........',
    '...PPP...P......',
    '..PPSSPPPPP.....',
    '..PSSSSSSSP.....',
    '.PSSPPPPPSSP....',
    '.PSPEWPPPWEP....',
    '.PSSPPPPPPSS....',
    '.PSSSPSSSPSS....',
    '..PSSSSSSSS.....',
    '...PPPPPPPP.....',
    '..SSPPPPPPSS....',
    '.SSPPPPPPPPSS...',
    '.SS.PP..PP.SS...',
    '.SS.PP..PP.SS...',
    '.SS........SS...',
    '................',
  ],
  tiger: [
    '....PP....PP....',
    '...PPP...PPP....',
    '..PPPPPPPPPP....',
    '.PPPPPPPPPPPP...',
    '.PPSEWPPWEPSPP..',
    '.PPPSSPPSSPPPP..',
    '.PPPPPPPPPPPP...',
    '..PPSSPPSSPP....',
    '...PPPPPPPP.....',
    '..SSPPPPPPSS....',
    '.SSPPPPPPPPSS...',
    '.SS.PP..PP.SS...',
    '.SS.PP..PP.SS...',
    '.SS........SS...',
    '................',
  ],
  leopard: [
    '....PP....PP....',
    '...PPP...PPP....',
    '..PPPPPPPPPP....',
    '.PPPPPPPPPPPP...',
    '.PPEWPPPPWEPP...',
    '.PPPPSSSPPPPP...',
    '.PPPSPPPSPPPP...',
    '..PPPPPPPPPP....',
    '...PPPPPPPP.....',
    '..SSPPPPPPSS....',
    '.SSPPPPPPPPSS...',
    '.SS.PP..PP.SS...',
    '.SS.PP..PP.SS...',
    '.SS........SS...',
    '................',
  ],
  elephant: [
    '.....PPPPPP.....',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '..PWWPPPPPPWWP..',
    '.PWEEPPPPPEEWP..',
    '.PWWPPPPPPPPWP..',
    '..PPPPPPPPPPPP..',
    '..PPPPPPPPPPPP..',
    '.SSPPPPPPPPSS...',
    '.SSPPPPPPPPSS...',
    '..SPPPPPPPPS....',
    '..SPPPPPPPPS....',
    '..S..PP..PP.....',
    '..S..PP..PP.....',
    '.....PP..PP.....',
    '................',
  ],
  monkey: [
    '.....PPPP......',
    '...PPSSSSP...PP.',
    '..PPSSSSSSPPPPP.',
    '..PSSSSSSSSPPP..',
    '.PSSPEWPPWEPS...',
    '.PSSPPPPPPPPS...',
    '.PSSSPSSSPSS....',
    '..PSSSSSSSS.....',
    '...PPPPPPPP.....',
    '..SSPPPPPPSS....',
    '.SSPPPPPPPPSS...',
    '.SS.PP..PP.SS...',
    '.SS.PP..PP.SS...',
    '.SS........SS...',
    '................',
  ],
  panda: [
    '...SS......SS...',
    '..SSS......SSS..',
    '.SSSSSSSSSSSSSS.',
    '.SSWWSSSSSSWWSS.',
    '.SWEESSSSSSEESS.',
    '.SSWWSSSSSSWWSS.',
    '..SSSSSSSSSSSS..',
    '...SSSSSSSSSS...',
    '....SSSSSSSS....',
    '...SSWWWWWWSS...',
    '..SSWWWWWWWWSS..',
    '..SS.WW..WW.SS..',
    '..SS.WW..WW.SS..',
    '..SS........SS..',
    '................',
  ],
  sheep: [
    '....PPPPPPPP....',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '.PPWPPPPPPWPPP..',
    '.PWEEPPPPWEEPP..',
    '.PWWPPPPPPWWPP..',
    '.SPPPPPPPPPPSP..',
    '.SPPSSSSSSSSPS..',
    '..SPPPPPPPPSP..',
    '..SPPPPPPPPSP..',
    '...SPPPPPPPS....',
    '...SPPPPPPPS....',
    '....SS..SS......',
    '....SS..SS......',
    '...SSS..SSS.....',
    '................',
  ],
  cow: [
    '.WW..........WW.',
    '.WPPPPPPPPPPW..',
    '..PPPPPPPPPP....',
    '.PPWPPPPPPWPPP..',
    '.PWEEPPPPWEEPP..',
    '.PWWPPPPPPWWPP..',
    '.SPPPPPPPPPPSP..',
    '.SPPSSSSSSSSPS..',
    '..SPPPPPPPPSP..',
    '..SPPPPPPPPSP..',
    '...SPPPPPPPS....',
    '...SPPPPPPPS....',
    '....SS..SS......',
    '....SS..SS......',
    '...SSS..SSS.....',
    '................',
  ],
  horse: [
    '......PPPPPP....',
    '.....PPPPPPPP...',
    '....PEWPPPPPP...',
    '....PPPPPPPP....',
    '....PPPPPPPSS...',
    '....PPPPPPSSS...',
    '....PPPPPPSS....',
    '....PPPPPP......',
    '....PPPPPP......',
    '...SSPPPPSS.....',
    '..SSPPPPPPSS....',
    '..SS..PP..SS....',
    '..SS..PP..SS....',
    '..SS..PP..SS....',
    '..SS..PP..SS....',
    '................',
  ],
  pig: [
    '....PPPPPPPP....',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '.PPEWPPPPWEPPP..',
    '.PPPPPPPPPPPP...',
    '.PPPSSSSSSPPPP..',
    '.PPPSEEEESPPPP..',
    '.PPPSSSSSSPPPP..',
    '..PPPPPPPPPP....',
    '...PPPPPPPP.....',
    '..SSPPPPPPSS....',
    '.SSPPPPPPPPSS...',
    '.SS.PP..PP.SS...',
    '.SS.PP..PP.SS...',
    '.SS........SS...',
    '................',
  ],
  frog: [
    '...PP......PP...',
    '..PEWP....PEWP..',
    '..PPPP....PPPP..',
    '.PPPPPPPPPPPPPP.',
    '.PPPPPPPPPPPPPP.',
    '.PPPPSSSSPSSSSP.',
    '.PPPPSSSSSSSSSP.',
    '..PPPPPPPPPPPP..',
    '...PPPPPPPPPP...',
    '..SSPPPPPPPSSS..',
    '.SSSPPPPPPSSSS..',
    '.SS..PPPP..SSS..',
    '.....PPPP.......',
    '.....PP.PP......',
    '....SSS.SSS.....',
    '................',
  ],
  turtle: [
    '......PPPP......',
    '....PPPPPPPP....',
    '...PPEWPPWEPP...',
    '...PPPPPPPPPP...',
    '..SSSSSSSSSSSS..',
    '.SSSSSSSSSSSSSS.',
    '.SSSPPPSSSPPPSS.',
    '.SSPPPPPPPPPPSS.',
    '.SSSPPPSSSPPPSS.',
    '.SSSSSSSSSSSSSS.',
    '..SSSSSSSSSSSS..',
    '...SS......SS...',
    '...SS......SS...',
    '..SSS......SSS..',
    '................',
  ],
  penguin: [
    '......PPPP......',
    '....PPWWWWPP....',
    '...PPWEEWWEPP...',
    '...PPWWWWWWPP...',
    '...PPWWWWWWPP...',
    '..PPPWWWWWWPPP..',
    '..PPPPWWWWPPPP..',
    '.PPPPPWWWWPPPPP.',
    '.PPPPPPWWPPPPPP.',
    '.PPPPPPWWPPPPPP.',
    '..PPPPWWWWPPPP..',
    '...PPWWWWWWPP...',
    '...PPWWWWWWPP...',
    '....SSSSSSSS....',
    '....SSSSSSSS....',
    '................',
  ],
  mouse: [
    '..PPP......PPP..',
    '.PPPPP....PPPPP.',
    '.PPSSPP..PPSSPP.',
    '.PPSSPPPPPPSSPP.',
    '..PPPPPPPPPP....',
    '..PEWPPPPWEP....',
    '..PPPPPPPPPP....',
    '...PPPSSSPPP....',
    '....PPPPPP......',
    '....PPPPPP......',
    '...SSPPPPSS.....',
    '..SSPPPPPPSS....',
    '..SS..PP..SS....',
    '..SS..PP..SS....',
    '..SS......SS....',
    '................',
  ],
  squirrel: [
    '...PP......PP...',
    '..PPP......PPP..',
    '..SPPP....PPPS..',
    '..SSPPPPPPPPSS..',
    '..PEWPPPPWEPP...',
    '..PPPPPPPPPP....',
    '..PPWPSSSPWPP...',
    '..PPPPPPPPPP....',
    '..PPPPPPSSSS....',
    '..PPPPPPSSSSS...',
    '..SSPPPPPPSSS...',
    '.SSSPPPPPPSSS...',
    '.SS..PP.PP.SS...',
    '.SS..PP.PP.SS...',
    '.....SS.SS......',
    '................',
  ],
  bat: [
    '......PP........',
    '....PPPPPP......',
    '...PPEWPPWEP....',
    '...PPPPPPPPPP...',
    '..PP..PPPP..PP..',
    '.PPP..PPPP..PPP.',
    '.PPP..PPPP..PPP.',
    'PPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPP',
    '.PPP..PPPP..PPP.',
    '.PP....PP....PP.',
    '..P....PP....P..',
    '.......PP.......',
    '......SSSS......',
    '......SSSS......',
    '................',
  ],
  spider: [
    '......PPPP......',
    '....PPPPPPPP....',
    '...PEWPPWEPP...',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '.PP.PPPPPPPP.PP.',
    '.PP.PPPPPPPP.PP.',
    'PPPP.PPPPPP.PPPP',
    'PPPP.PPPPPP.PPPP',
    '.PP.PPPPPPPP.PP.',
    '.PP.PPPPPPPP.PP.',
    '..P.PPPPPPPP.P..',
    '......PPPP......',
    '......PPPP......',
    '................',
  ],
  bee: [
    '......PPPP......',
    '....PPPPPPPP....',
    '...PEWPPWEPP...',
    '...PPPPPPPPPP...',
    '..PPPPSSSSPPPP..',
    '.PPSSWWWWWWSSPP.',
    '.PPSSWWWWWWSSPP.',
    'PPSSPPPPPPSSPP',
    'PPSSPPPPPPSSPP',
    '.PPSSWWWWWWSSPP.',
    '.PPSSWWWWWWSSPP.',
    '..PPPPSSSSPPPP..',
    '....PPPPPPPP....',
    '......PPPP......',
    '................',
  ],
  butterfly: [
    '..WW......WW....',
    '.WWW......WWW...',
    '.WWWW....WWWW...',
    '.WWPEWPPWEPWW...',
    '.WWWWPPPPWWWW...',
    '.SSWWPPPPWWSS...',
    '.SSSWWPPWWSSS...',
    '.SSSSPPPPSSSS...',
    '..SSSPPPPSSS...',
    '...SSPPPPSS.....',
    '....SSPPSS......',
    '.....SSSS.......',
    '......SS........',
    '......SS........',
    '......SS........',
    '................',
  ],
  crab: [
    '.WW........WW...',
    '.WWW......WWW...',
    '.WWWW....WWWW...',
    '..PPPPPPPPPP....',
    '..PEWPPPPWEP....',
    '..PPPPPPPPPP....',
    '.PPPPPPPPPPPP...',
    '.PPPPPPPPPPPP...',
    '.P.P.P..P.P.P...',
    '.P.P.P..P.P.P...',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  octopus: [
    '......PPPP......',
    '....PPPPPPPP....',
    '...PEWPPWEPP...',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '..PPPPPPPPPPPP..',
    '..PPPPPPPPPPPP..',
    '...PPPPPPPPPP...',
    '.PP.PP.PP.PP.PP.',
    '.PP.PP.PP.PP.PP.',
    '.PP.PP.PP.PP.PP.',
    '..P..P..P..P..P.',
    '................',
    '................',
    '................',
    '................',
  ],
  shark: [
    '........PP......',
    '.......PPPP.....',
    '......PPPPPP....',
    '....PPPPPPPPPP..',
    '...PEWPPPPPPPP..',
    '..PPPPPPPPPPSS..',
    '.PPPPPPPPPPSSS..',
    'PPPPPPPPPPPPSS..',
    '.PPPPPPPPPPPP...',
    '..PPPPPPPPPP....',
    '...PPPPPPPP.....',
    '....PPPPPP......',
    '.....PPPP.......',
    '......SS........',
    '......SS........',
    '................',
  ],
  whale: [
    '......WW........',
    '......WW........',
    '....PPPPPPPP....',
    '..PPPPPPPPPPPP..',
    '.PEWPPPPPPPPPP..',
    '.PPPPPPPPPPPPPSS',
    '.PPPPPPPPPPPPSSS',
    '.PPPPPPPPPPPSSS.',
    '..PPPPPPPPPPSSS.',
    '...PPPPPPPPSS...',
    '....PPPPPP......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  dolphin: [
    '........PP......',
    '.......PPPP.....',
    '......PPPPPP....',
    '....PPPPPPPPPP..',
    '...PEWPPPPPPPP..',
    '..PPPPPPPPPPPP..',
    '.PPPPPPPPPPPP...',
    '.PPPPPPPPPPSS...',
    '..PPPPPPPPSSS...',
    '...PPPPPPPPSS...',
    '....PPPPPP......',
    '.....PPPP.......',
    '......SS........',
    '......SS........',
    '................',
  ],
  eagle: [
    '......PPP.......',
    '.....PPPPP......',
    '....PEWPPPP.....',
    '...PPPPPPPPSS...',
    '..PPPPPPPPSSS...',
    '.PPPPPPPPPPPP...',
    '.PPPPPPPPPPPP...',
    'PPPPPPPPPPPPPP..',
    'PPPPPPPPPPPPPP..',
    '.PPPPPPPPPPPP...',
    '..PPPPPPPPPP....',
    '...PPPPPPPP.....',
    '....PPPP........',
    '...SS..SS.......',
    '...SS..SS.......',
    '..SSS..SSS......',
  ],
  phoenix: [
    '......PPP.......',
    '.....PPPPP......',
    '....PEWPPPP.....',
    '...PPPPPPPPSS...',
    '..PPPPPPPPSSS...',
    '.PPSSPPPPSSPP...',
    '.PSSSPPPSSSPP...',
    '.PSSSSPPSSSS....',
    '..SSSPPPPSSS....',
    '...SSPPPPSS.....',
    '....SSPPSS......',
    '.....SSSS.......',
    '......SS........',
    '.....SSSS.......',
    '....SSSSSS......',
    '...SSSSSSSS.....',
  ],
  unicorn: [
    '......W.........',
    '......WW........',
    '......PP........',
    '.....PPPP.......',
    '....PPPPPP......',
    '...PEWPPPPSS....',
    '...PPPPPPSSS....',
    '...PPPPPPSS.....',
    '...PPPPPP.......',
    '...PPPPPP.......',
    '..SSPPPPSS......',
    '.SSPPPPPPSS.....',
    '.SS..PP..SS.....',
    '.SS..PP..SS.....',
    '.SS..PP..SS.....',
    '................',
  ],
  pegasus: [
    '......PP........',
    '.....PPPP.......',
    '....PPPPPP......',
    '...PEWPPPPSS....',
    '...PPPPPPSSS....',
    '.WWPPPPPPSS.....',
    '.WWPPPPPP.......',
    '.WWPPPPPP.......',
    '..SSPPPPSS......',
    '.SSPPPPPPSS.....',
    '.SS..PP..SS.....',
    '.SS..PP..SS.....',
    '.SS..PP..SS.....',
    '................',
  ],
  koala: [
    '.PPP........PPP.',
    'PPPPP......PPPPP',
    'PPSSPP....PPSSPP',
    'PPSSPPPPPPSSPP',
    '.PPPPPPPPPP.....',
    '.PEWPPSSPPWEP...',
    '.PPPPSSPPPP.....',
    '.PPPPPSSPPPPP...',
    '..PPPPPPPPPP....',
    '...PPPPPPPP.....',
    '..SSPPPPPPSS....',
    '.SSPPPPPPPPSS...',
    '.SS.PP..PP.SS...',
    '.SS.PP..PP.SS...',
    '.SS........SS...',
    '................',
  ],
  kangaroo: [
    '....PP..........',
    '...PPP..........',
    '...PPP..........',
    '...PPPPPP.......',
    '..PEWPPPPSS.....',
    '..PPPPPPSSS.....',
    '..PPPPPPSS......',
    '..PPPPPP........',
    '..PPPPPP........',
    '..PPPPPPPP......',
    '...PPPPPPPP.....',
    '....PPPPPPSS....',
    '....SS.PP.SS....',
    '...SSS....SSS...',
    '................',
  ],
  duck: [
    '......PPPP......',
    '....PPSSPPPP....',
    '...PEWSSPPPP....',
    '...PPPPPPPP.....',
    '....PPPPPP......',
    '...PPPPPPPP.....',
    '..PPPPPPPPPP....',
    '.PPPPPPPPPPPP...',
    '.PPPPPPPPPPPP...',
    '.PPPPPPPPPPPP...',
    '..PPPPPPPPPP....',
    '...PPPPPPPP.....',
    '....SSSSSSSS....',
    '....SSSSSSSS....',
    '................',
  ],
  chicken: [
    '......WW........',
    '.....WWPP.......',
    '....PPPEW.......',
    '....PPPPPP......',
    '....PPPPPP......',
    '...PPPPPPPP.....',
    '..PPPPPPPPPP....',
    '.PPPPPPPPPPPP...',
    '.PPPPPPPPPPPP...',
    '.PPPPPPPPPPPP...',
    '..PPPPPPPPPP....',
    '...PPPPPPPP.....',
    '....SSSSSSSS....',
    '....SSSSSSSS....',
    '................',
  ],
  goat: [
    '..WW........WW..',
    '..PP........PP..',
    '.PPPP......PPPP.',
    '.PPPPPPPPPPPPPP.',
    '..PPWPPPPPPWPP..',
    '.PWEEPPPPWEEPP..',
    '.PWWPPPPPPWWPP..',
    '..PPPPPPPPPP....',
    '...PPPPPPPP.....',
    '..SSPPPPPPSS....',
    '.SSPPPPPPPPSS...',
    '.SS.PP..PP.SS...',
    '.SS.PP..PP.SS...',
    '.SS........SS...',
    '................',
  ],
  scorpion: [
    '....WW..........',
    '....WW..........',
    '...PPPP.........',
    '...PPPP.........',
    '..PPPPPP........',
    '..PEWPPWEP......',
    '..PPPPPPPP......',
    '...PPPPPP.......',
    '...PPPPPP.......',
    '..PPPPPPPP......',
    '.PPPPPPPPPP.....',
    '.PP......PP.....',
    '.P........P.....',
    '................',
    '................',
    '................',
  ],
  caterpillar: [
    '................',
    '................',
    '......PPPP......',
    '....PPPPPPPP....',
    '...PEWPPWEPP...',
    '...PPPPPPPPPP...',
    '..PPPPPPPPPPPP..',
    '..P.P.P.P.P.P...',
    '..S.S.S.S.S.S...',
    '..P.P.P.P.P.P...',
    '..SSSSSSSSSS....',
    '...SSSSSSSS.....',
    '................',
    '................',
    '................',
    '................',
  ],
  lobster: [
    '.WW........WW...',
    '.WWW......WWW...',
    '..PPPPPPPPPP....',
    '..PEWPPPPWEP....',
    '..PPPPPPPPPP....',
    '.PPPPPPPPPPPP...',
    '.P.PPPPPPPP.P...',
    '.P..PPPPPP..P...',
    '....PPPPPP......',
    '...SSSSSS.......',
    '...SSSSSS.......',
    '..PPPPPPPP......',
    '..P......P......',
    '................',
    '................',
    '................',
  ],
  squid: [
    '......PP........',
    '.....PPPP.......',
    '....PPPPPP......',
    '...PEWPPWEP.....',
    '...PPPPPPPP.....',
    '..PPPPPPPPPP....',
    '..PPPPPPPPPP....',
    '..PPPPPPPPPP....',
    '...PPPPPPPP.....',
    '...P.P.P.P......',
    '...P.P.P.P......',
    '..PP.P.P.PP.....',
    '..P.PP.PP.P.....',
    '..P.P...P.P.....',
    '................',
    '................',
  ],
  dinosaur: [
    '.....PPPPPP.....',
    '...PPPPPPPPPP...',
    '..PPEWPPPPPP....',
    '..PPPPPPPP......',
    '..PPPPPPPP......',
    '..PPPPPPPP......',
    '..PPPPPPPP......',
    '..PPPPPPPPPPPP..',
    '..PPPPPPPPPPPPSS',
    '..PPPPPPPPPPSSSP',
    '...PPPPPPPPSS...',
    '....PPPPPP......',
    '...SSPPPPSS.....',
    '..SSPPPPPPSS....',
    '..SS......SS....',
    '................',
  ],
};

function parsePattern(species: SpiritSpecies): PixelGrid {
  return PATTERNS[species].map(
    row => row.split('') as PixelChar[]
  );
}

// ─── Props ────────────────────────────────────────────

export interface WordSpiritAvatarProps {
  wordId: string;
  wordScore: number;       // 用於決定等級 / 大小
  animState?: 'appear' | 'idle' | 'captured' | 'escaped';
}

// ─── 元件 ─────────────────────────────────────────────

const WordSpiritAvatar: React.FC<WordSpiritAvatarProps> = ({
  wordId,
  wordScore,
  animState = 'idle',
}) => {
  const spirit = useMemo(() => generateWordSpirit(wordId), [wordId]);
  const level  = useMemo(() => getSpiritLevel(wordScore), [wordScore]);
  const size   = useMemo(() => getSpiritSize(level), [level]);
  const grid   = useMemo(() => parsePattern(spirit.species), [spirit.species]);

  const GRID_SIZE = 16;
  const cellSize  = size / GRID_SIZE;

  const colorMap: Record<PixelChar, string> = {
    '.': 'transparent',
    'P': spirit.primaryColor,
    'S': spirit.secondaryColor,
    'E': level >= 3 ? '#FF2222' : '#111111',  // Lv3 → 紅眼
    'W': '#FFFFFF',
  };

  // 動畫 class
  const animClass =
    animState === 'appear'   ? 'spirit-appear'   :
    animState === 'captured' ? 'spirit-captured'  :
    animState === 'escaped'  ? 'spirit-escaped'   :
                               'spirit-idle';

  // 等級光暈
  const glowClass =
    level >= 3 ? 'spirit-glow-intense' :
    level >= 2 ? 'spirit-glow-mild'    :
                 '';

  return (
    <div className="flex flex-col items-center gap-2">
      {/* 等級標示 */}
      <div className={`font-pixel text-[10px] tracking-wider ${
        level >= 3 ? 'text-red-400 animate-pulse' :
        level >= 2 ? 'text-orange-400' :
                     'text-primary/60'
      }`}>
        {level >= 3 ? '★★★ BERSERK' : level >= 2 ? '★★ EVOLVED' : '★ NORMAL'}
      </div>

      {/* 像素動物 SVG */}
      <div className={`${animClass} ${glowClass} relative`}>
        {level >= 2 && (
          <div className="absolute inset-0 spirit-aura" style={{
            boxShadow: level >= 3
              ? '0 0 20px rgba(255,34,34,0.6), 0 0 40px rgba(255,34,34,0.3)'
              : '0 0 12px rgba(232,168,56,0.4), 0 0 24px rgba(232,168,56,0.2)',
          }} />
        )}
        <svg
          width={size}
          height={size}
          viewBox={`0 0 ${GRID_SIZE} ${GRID_SIZE}`}
          className="image-rendering-pixelated"
          style={{ imageRendering: 'pixelated' }}
        >
          {grid.map((row, y) =>
            row.map((cell, x) => {
              if (cell === '.') return null;
              return (
                <rect
                  key={`${x}-${y}`}
                  x={x}
                  y={y}
                  width={1}
                  height={1}
                  fill={colorMap[cell]}
                />
              );
            })
          )}
        </svg>
      </div>

      {/* 詞靈名稱 */}
      <div className={`font-pixel text-sm tracking-widest ${
        level >= 3 ? 'text-red-400' :
        level >= 2 ? 'text-orange-300' :
                     'text-primary/80'
      }`}>
        {spirit.spiritName}
        {level >= 2 && <span className="ml-1 text-[10px] opacity-70">Lv.{level}</span>}
      </div>
    </div>
  );
};

export default WordSpiritAvatar;
